### ISSUE TITLE
Crashes When Clicking Xbox Live Related Links

### ISSUE THREAD

**Issue by BrainBlasted** [kris27mc/minecraft-linux#16]
### System:

* **OS:** Arch Linux
* **GPU:** Intel HD 4000
* **CPU:** i7-3630QM 
* **Version:** Latest
### Issue Description:

Minecraft-linux closes when clicking any links related to Xbox live. My browser was closed, if this information is relevant.

**Comment by kris27mc** [comment]
This is a currently known issue. I'm mostly waiting for it to be resolved [upstream](https://github.com/MCMrARM/mcpelauncher-linux), as it should be soon. If not soon enough, I'll probably try to implement my own solution though! I'd very much need help doing so, but I can try to get something done about this **ASAP**.   

The original dev has stated that he feels it would be difficult to implement using QT due to incompatibilities with the i386 (32-bit) architecture, as well as implementing Chromium being too difficult/cumbersome.   
Personally, being an Arch user, and someone who promotes progression, I have no frills with dropping 32-bit support (as Arch will later this year), so even if it doesn't make it upstream, I may try to get help implementing my own makeshift built-in browser in some form.

**Comment by BrainBlasted** [comment]
Yes, I can play the game proper after closing the Xbox notification. Runs buttery smooth, as well.

**Comment by kris27mc** [comment]
The original dev, @MCMrARM, has plans to implement a browser, thus allowing support for Xbox Live sign-in. It's only a matter of time before it's supported (:

**Comment by kris27mc** [comment]
Support for Xbox Live is almost within reach! It will be implemented fairly soon!

**Comment by BrainBlasted** [comment]
Yay! Theoretically, this would allow me to play with friends on Windows 10,
Nintendo, and Xbox, correct?

**Comment by kris27mc** [comment]
It absolutely should! As far as I see it, this project (my fork and the original) is the Linux equivalent of the Windows 10 Edition, and should hold Linux over when they do finally kill off the Java Edition.

**Comment by kris27mc** [comment]
You'll need a 1.2 apk, but `1.2-dev` now has Xbox Live support. I've integrated everything MCMrARM has committed to his Xbox Live branch. The only pitfall being I only provide the latest stable apk, and 1.2 stable is yet to be released, so you'll have to acquire a 1.2 beta apk. For testing purposes, if you need one, and you have [Telegram](https://t.me/minecraftlinux), I can send it to you there. Or if there's an alternative method you like.  
Also, I don't actually have the latest stable apk as I have no way of getting it. BUT, that's in other news.
MCMrARM is currently working on a method of fixing [Google-Play-API](https://github.com/MCMrARM/Google-Play-API).
